### ISSUE TITLE
Speed of this repo

### ISSUE THREAD

**Issue by GoingMyWay** [kenjyoung/MinAtar#10]
Hi, for Atari games, normally running 200M steps will cost 8-10 days. So, for this repo, how long it will take to run 200M steps?

**Comment by kenjyoung** [comment]
I assume you mean training an agent v.s. just running the emulator, as running the ATARI emulator alone for 200M steps will take much less than 8-10 days. In this case, it will depend highly on the architecture you are using. Also, I'm not totally sure but I think the 8-10 days you're referencing to is 200 emulator frames, which with the usual frame-skip of 4 is really only 50 million updates. We do not use frame-skipping in MinAtar, nor recommend it since each frame is more information-rich than ATARI games. We found the DQN architecture in our repo to run at about 5 ms per update on GPU (or 8 ms on CPU), for 50 million updates this would be around 3 days. For 200 million it would be around 11-12 days, but we wouldn't generally suggest training an agent in MinAtar for this long.

**Comment by GoingMyWay** [comment]
> I assume you mean training an agent v.s. just running the emulator, as running the ATARI emulator alone for 200M steps will take much less than 8-10 days. In this case, it will depend highly on the architecture you are using. Also, I'm not totally sure but I think the 8-10 days you're referencing to is 200 emulator frames, which with the usual frame-skip of 4 is really only 50 million updates. We do not use frame-skipping in MinAtar, nor recommend it since each frame is more information-rich than ATARI games. We found the DQN architecture in our repo to run at about 5 ms per update on GPU (or 8 ms on CPU), for 50 million updates this would be around 3 days. For 200 million it would be around 11-12 days, but we wouldn't generally suggest training an agent in MinAtar for this long.

Thank you.
