### ISSUE TITLE
Compatibility with stable-baselines3

### ISSUE THREAD

**Issue by jilljenn** [kenjyoung/MinAtar#26]
Hi, I am not sure that the repo is gym-compatible, as I get errors from stable-baselines3:

```python
env = make_atari_env('MinAtar/Breakout-v0', n_envs=1, seed=0)
```

    AttributeError: 'BaseEnv' object has no attribute 'get_action_meanings'

```python
from stable_baselines3.common.env_checker import check_env
check_env(env)
```

    AssertionError: The observation returned by the `reset()` method should be a single value, not a tuple

**Comment by jilljenn** [comment]
OK I think I made a fix, will PR soon

**Comment by kenjyoung** [comment]
Hey, I think the issue is with the version of gym. I recently updated it for consistency with the newest gym version which has a slightly different API. This broke compatibility with the older versions. I suppose it would be good to somehow make it work with both (perhaps by checking the gym version). 

In the meantime, if you require the old gym version you can use version 1.0.11 of MinAtar. For example by running:
`pip install minatar==1.0.11`
